# Constants for shared memory protocol
REPORT_OFFSET = 3
REPORT_SIZE = 11
REQUEST_SIGNAL_INDEX = 0
REQUESTED_REPORTS_NUMBER_INDEX = 1 
COMPLETION_SIGNAL_INDEX = 2
CUP_DETECTION_FLAG = REPORT_OFFSET
X_CENTER_INDEX = REPORT_OFFSET + 1
CUP_COLOR_CLASS_INDEX = REPORT_OFFSET + 2
RELATIVE_SIZE_INDEX_START = REPORT_OFFSET + 3
RELATIVE_SIZE_INDEX_END = REPORT_OFFSET + 3 + 8 # relative_size is encoded to 1 byte (which represents a float), so it's 8 bits, meaning it takes 8 indexes.
